# Generated by Django 4.2.3 on 2023-07-09 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='breed',
            old_name='trainablity',
            new_name='trainability',
        ),
    ]
